//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentsPayeurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentsPayeurs()
        {
            this.CommandesCylindres = new HashSet<CommandesCylindres>();
            this.Usagers = new HashSet<Usagers>();
        }
    
        public int AgentPayeurID { get; set; }
        public string Nom { get; set; }
        public bool EstActif { get; set; }
        public string Description { get; set; }
        public string Adresse { get; set; }
        public string Telephone { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public string UtilisateurCreation { get; set; }
        public string UtilisateurModification { get; set; }
        public Nullable<int> TypeFinancementID { get; set; }
        public string AgentPayeurCode { get; set; }
    
        public virtual TypesFinancementRef TypesFinancementRef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommandesCylindres> CommandesCylindres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usagers> Usagers { get; set; }
    }
}
