//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignations()
        {
            this.AssignationsRemplacants = new HashSet<AssignationsRemplacants>();
        }
    
        public int AssignationID { get; set; }
        public int UsagerID { get; set; }
        public int TypeIntervenantID { get; set; }
        public int IntervenantID { get; set; }
        public Nullable<int> StatutSuiviID { get; set; }
        public Nullable<int> FrequenceValeur { get; set; }
        public string FrequenceUnite { get; set; }
        public Nullable<System.DateTime> DerniereVisiteDate { get; set; }
        public Nullable<int> DerniereVisiteDureeMinutes { get; set; }
        public Nullable<System.DateTime> ProchaineVisiteDate { get; set; }
        public System.DateTime DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string ModifieParUserId { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Intervenants Intervenants { get; set; }
        public virtual StatutsSuivi StatutsSuivi { get; set; }
        public virtual TypesIntervenant TypesIntervenant { get; set; }
        public virtual Usagers Usagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignationsRemplacants> AssignationsRemplacants { get; set; }
    }
}
