//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandesCylindres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommandesCylindres()
        {
            this.CommandeCylindreLignes = new HashSet<CommandeCylindreLignes>();
        }
    
        public int CommandeID { get; set; }
        public int UsagerID { get; set; }
        public int FournisseurID { get; set; }
        public Nullable<int> AgentPayeurID { get; set; }
        public string CentreDeCout { get; set; }
        public string BonCommande { get; set; }
        public int TypeLivraisonID { get; set; }
        public int MotifCommandeID { get; set; }
        public Nullable<System.DateTime> DateLivraisonDemandee { get; set; }
        public string Commentaire { get; set; }
        public string Statut { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AgentsPayeurs AgentsPayeurs { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommandeCylindreLignes> CommandeCylindreLignes { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
        public virtual TypesLivraisonRef TypesLivraisonRef { get; set; }
        public virtual MotifsCommandeCylindreRef MotifsCommandeCylindreRef { get; set; }
        public virtual Usagers Usagers { get; set; }
    }
}
