//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandeCylindreLignes
    {
        public int LigneID { get; set; }
        public int CommandeID { get; set; }
        public int TypeCylindreID { get; set; }
        public int Quantite { get; set; }
        public decimal PrixUnitaire { get; set; }
        public Nullable<decimal> PrixTotal { get; set; }
    
        public virtual CommandesCylindres CommandesCylindres { get; set; }
        public virtual TypesCylindreRef TypesCylindreRef { get; set; }
    }
}
