//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entretiens
    {
        public int EntretienID { get; set; }
        public int EquipementID { get; set; }
        public System.DateTime DateEntretien { get; set; }
        public Nullable<int> LectureID { get; set; }
        public string DetailsJSON { get; set; }
        public string Commentaire { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Equipements Equipements { get; set; }
        public virtual LecturesCompteur LecturesCompteur { get; set; }
    }
}
