//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipements()
        {
            this.ControlesQualite = new HashSet<ControlesQualite>();
            this.Entretiens = new HashSet<Entretiens>();
            this.HistoriqueStatutsEquipement = new HashSet<HistoriqueStatutsEquipement>();
            this.LecturesCompteur = new HashSet<LecturesCompteur>();
            this.Pannes = new HashSet<Pannes>();
            this.PretsEquipement = new HashSet<PretsEquipement>();
        }
    
        public int EquipementID { get; set; }
        public int TypeEquipementID { get; set; }
        public string NoInventaireSRSAD { get; set; }
        public string Modele { get; set; }
        public string NumeroSerie { get; set; }
        public Nullable<int> FournisseurID { get; set; }
        public Nullable<int> ManufacturierID { get; set; }
        public Nullable<int> UsagerAchatID { get; set; }
        public Nullable<System.DateTime> DateAchat { get; set; }
        public Nullable<System.DateTime> DateFacturation { get; set; }
        public Nullable<decimal> PrixAchat { get; set; }
        public Nullable<System.DateTime> DateLivraisonCEMTL { get; set; }
        public Nullable<System.DateTime> DateMiseEnService { get; set; }
        public Nullable<int> GarantieNbAnnees { get; set; }
        public Nullable<System.DateTime> GarantieFin { get; set; }
        public Nullable<int> DureeVieMois { get; set; }
        public Nullable<int> TypeAcquisitionID { get; set; }
        public string AgentPayeurAcquisition { get; set; }
        public string BonCommandeAcquisition { get; set; }
        public string StatutTabagique { get; set; }
        public bool EstFumeurIrreversible { get; set; }
        public bool EstInfestation { get; set; }
        public bool EstInfection { get; set; }
        public string Commentaires { get; set; }
        public bool EstActif { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string ModifieParUserId { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlesQualite> ControlesQualite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entretiens> Entretiens { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
        public virtual Manufacturiers Manufacturiers { get; set; }
        public virtual TypesEquipement TypesEquipement { get; set; }
        public virtual TypesAcquisitionRef TypesAcquisitionRef { get; set; }
        public virtual Usagers Usagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriqueStatutsEquipement> HistoriqueStatutsEquipement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LecturesCompteur> LecturesCompteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pannes> Pannes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PretsEquipement> PretsEquipement { get; set; }
    }
}
