//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GabaritsEntretien
    {
        public int GabaritID { get; set; }
        public int TypeEquipementID { get; set; }
        public string Modele { get; set; }
        public Nullable<int> HeuresEntreControles { get; set; }
        public Nullable<int> HeuresEntreEntretiens { get; set; }
        public Nullable<int> MargeErreurHeures { get; set; }
        public bool EstActif { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TypesEquipement TypesEquipement { get; set; }
    }
}
