//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportFacturationCylindres
    {
        public int ImportID { get; set; }
        public int FournisseurID { get; set; }
        public Nullable<int> PeriodeFinID { get; set; }
        public string NomFichier { get; set; }
        public System.DateTime DateImport { get; set; }
        public string ImporteParUserId { get; set; }
        public string Statut { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
        public virtual PeriodesFinancieresRef PeriodesFinancieresRef { get; set; }
    }
}
