//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervenants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intervenants()
        {
            this.Assignations = new HashSet<Assignations>();
            this.AssignationsRemplacants = new HashSet<AssignationsRemplacants>();
            this.Visites = new HashSet<Visites>();
        }
    
        public int IntervenantID { get; set; }
        public int TypeIntervenantID { get; set; }
        public Nullable<int> CLSCID { get; set; }
        public Nullable<int> SecteurID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public bool EstActif { get; set; }
        public string UserIdAspNet { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string ModifieParUserId { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignations> Assignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignationsRemplacants> AssignationsRemplacants { get; set; }
        public virtual CLSC CLSC { get; set; }
        public virtual SecteursSRSAD SecteursSRSAD { get; set; }
        public virtual TypesIntervenant TypesIntervenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visites> Visites { get; set; }
    }
}
