//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalAudit
    {
        public long AuditID { get; set; }
        public System.DateTime DateHeure { get; set; }
        public string Action { get; set; }
        public string TableConcernee { get; set; }
        public string ClePrimaire { get; set; }
        public string AnciennesValeurs { get; set; }
        public string NouvellesValeurs { get; set; }
        public string Description { get; set; }
        public string UtilisateurId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
