//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationID { get; set; }
        public string DestUserId { get; set; }
        public string CodeEvenement { get; set; }
        public string ObjetType { get; set; }
        public string ObjetId { get; set; }
        public string Message { get; set; }
        public bool EstLue { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
