//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pannes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pannes()
        {
            this.Reparations = new HashSet<Reparations>();
        }
    
        public int PanneID { get; set; }
        public int EquipementID { get; set; }
        public System.DateTime DatePanne { get; set; }
        public int TypePanneID { get; set; }
        public Nullable<byte> Gravite { get; set; }
        public string StatutPanne { get; set; }
        public string Description { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Equipements Equipements { get; set; }
        public virtual TypesPanneRef TypesPanneRef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reparations> Reparations { get; set; }
    }
}
