//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PretsEquipement
    {
        public int PretID { get; set; }
        public int EquipementID { get; set; }
        public int UsagerID { get; set; }
        public System.DateTime DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Commentaire { get; set; }
        public string ValideParUserId { get; set; }
        public Nullable<System.DateTime> DateValidation { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Equipements Equipements { get; set; }
        public virtual Usagers Usagers { get; set; }
    }
}
