//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReglesNotification
    {
        public int RegleNotifID { get; set; }
        public string CodeEvenement { get; set; }
        public string CritereJSON { get; set; }
        public string DestinatairesJSON { get; set; }
        public string Canal { get; set; }
        public bool EstActive { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
