//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparations
    {
        public int ReparationID { get; set; }
        public int PanneID { get; set; }
        public System.DateTime DateIntervention { get; set; }
        public string Resultat { get; set; }
        public Nullable<decimal> Cout { get; set; }
        public string Commentaire { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Pannes Pannes { get; set; }
    }
}
