//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecteursSRSAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecteursSRSAD()
        {
            this.CodesPostauxSecteur = new HashSet<CodesPostauxSecteur>();
            this.Intervenants = new HashSet<Intervenants>();
            this.Usagers = new HashSet<Usagers>();
        }
    
        public int SecteurID { get; set; }
        public string Code { get; set; }
        public string Nom { get; set; }
        public bool EstActif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodesPostauxSecteur> CodesPostauxSecteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervenants> Intervenants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usagers> Usagers { get; set; }
    }
}
