//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatutsEquipementRef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatutsEquipementRef()
        {
            this.HistoriqueStatutsEquipement = new HashSet<HistoriqueStatutsEquipement>();
        }
    
        public int StatutEquipementID { get; set; }
        public string Code { get; set; }
        public string Libelle { get; set; }
        public bool EstActif { get; set; }
        public bool DeclencheNotif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriqueStatutsEquipement> HistoriqueStatutsEquipement { get; set; }
    }
}
