//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usagers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usagers()
        {
            this.Assignations = new HashSet<Assignations>();
            this.CommandesCylindres = new HashSet<CommandesCylindres>();
            this.Equipements = new HashSet<Equipements>();
            this.PretsEquipement = new HashSet<PretsEquipement>();
            this.UsagerAdresses = new HashSet<UsagerAdresses>();
            this.UsagerInfections = new HashSet<UsagerInfections>();
            this.UsagerInfestations = new HashSet<UsagerInfestations>();
            this.UsagerParticularites = new HashSet<UsagerParticularites>();
            this.Visites = new HashSet<Visites>();
        }
    
        public int UsagerID { get; set; }
        public string NoDossierInterne { get; set; }
        public string NoDossierIPM { get; set; }
        public string NoDossierSRSAD { get; set; }
        public Nullable<System.DateTime> DateDerniereSyncEClinibase { get; set; }
        public string RAMQ { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string Sexe { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string CodePostal { get; set; }
        public string Pays { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> CLSCID { get; set; }
        public Nullable<int> SecteurID { get; set; }
        public Nullable<int> StatutDossierID { get; set; }
        public bool CodeHydroQuebec { get; set; }
        public Nullable<int> AgentPayeurID { get; set; }
        public string CentreDeCout { get; set; }
        public string BonCommande { get; set; }
        public string StatutTabagique { get; set; }
        public bool EstActif { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string ModifieParUserId { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public Nullable<bool> GrandConsommateur { get; set; }
        public string NoteGenerale { get; set; }
        public Nullable<int> AncienDossierTemporaire { get; set; }
        public Nullable<int> DossierRadie { get; set; }
        public string DossierPatrimoine { get; set; }
        public string DossierRecherche { get; set; }
        public Nullable<System.DateTime> DateCreationDossier { get; set; }
        public Nullable<System.DateTime> DateMiseAJour { get; set; }
        public string StatutSecondaire { get; set; }
        public Nullable<System.DateTime> DateStatutSecondaire { get; set; }
        public string Langue { get; set; }
        public string OrigineEthnique { get; set; }
        public string Adresse_2 { get; set; }
        public string Adresse_3 { get; set; }
        public string LienTelephonique_3 { get; set; }
        public string RueTransversale { get; set; }
        public string Hopital { get; set; }
        public string ProjetRecherche { get; set; }
        public string ProjetRechercheDossier { get; set; }
        public string AutreDossier_1 { get; set; }
        public string AutreDossier_2 { get; set; }
        public Nullable<int> DerniereReference { get; set; }
        public string Assurance { get; set; }
        public string NoAssurance { get; set; }
        public string NoRecouvrement { get; set; }
        public Nullable<System.DateTime> DateDernierChgmtTabagique { get; set; }
        public Nullable<bool> CitpyenneteCanadienne { get; set; }
    
        public virtual AgentsPayeurs AgentsPayeurs { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignations> Assignations { get; set; }
        public virtual CLSC CLSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommandesCylindres> CommandesCylindres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipements> Equipements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PretsEquipement> PretsEquipement { get; set; }
        public virtual SecteursSRSAD SecteursSRSAD { get; set; }
        public virtual StatutsDossierUsager StatutsDossierUsager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsagerAdresses> UsagerAdresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsagerInfections> UsagerInfections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsagerInfestations> UsagerInfestations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsagerParticularites> UsagerParticularites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visites> Visites { get; set; }
    }
}
