//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsagerAdresses
    {
        public int UsagerAdresseID { get; set; }
        public int UsagerID { get; set; }
        public string TypeAdresse { get; set; }
        public string SourceAdresse { get; set; }
        public bool EstCourante { get; set; }
        public string Adresse1 { get; set; }
        public string Adresse2 { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string CodePostal { get; set; }
        public string Pays { get; set; }
        public string Telephone { get; set; }
        public string Commentaire { get; set; }
        public Nullable<System.DateTime> DateDebutValidite { get; set; }
        public Nullable<System.DateTime> DateFinValidite { get; set; }
        public string EClinibaseAdresseId { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string ModifieParUserId { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Usagers Usagers { get; set; }
    }
}
