//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visites
    {
        public int VisiteID { get; set; }
        public int UsagerID { get; set; }
        public int IntervenantID { get; set; }
        public int TypeIntervenantID { get; set; }
        public System.DateTime DateVisite { get; set; }
        public Nullable<int> DureeMinutes { get; set; }
        public string Notes { get; set; }
        public string CreeParUserId { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Intervenants Intervenants { get; set; }
        public virtual TypesIntervenant TypesIntervenant { get; set; }
        public virtual Usagers Usagers { get; set; }
    }
}
