//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSAD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDbConnection : DbContext
    {
        public EntitiesDbConnection()
            : base("name=EntitiesDbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentsPayeurs> AgentsPayeurs { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Assignations> Assignations { get; set; }
        public virtual DbSet<AssignationsRemplacants> AssignationsRemplacants { get; set; }
        public virtual DbSet<CLSC> CLSC { get; set; }
        public virtual DbSet<CodesPostauxSecteur> CodesPostauxSecteur { get; set; }
        public virtual DbSet<CommandeCylindreLignes> CommandeCylindreLignes { get; set; }
        public virtual DbSet<CommandesCylindres> CommandesCylindres { get; set; }
        public virtual DbSet<ControlesQualite> ControlesQualite { get; set; }
        public virtual DbSet<Entretiens> Entretiens { get; set; }
        public virtual DbSet<Equipements> Equipements { get; set; }
        public virtual DbSet<Fournisseurs> Fournisseurs { get; set; }
        public virtual DbSet<GabaritsEntretien> GabaritsEntretien { get; set; }
        public virtual DbSet<HistoriqueStatutsEquipement> HistoriqueStatutsEquipement { get; set; }
        public virtual DbSet<ImportFacturationCylindres> ImportFacturationCylindres { get; set; }
        public virtual DbSet<Intervenants> Intervenants { get; set; }
        public virtual DbSet<JournalAudit> JournalAudit { get; set; }
        public virtual DbSet<LecturesCompteur> LecturesCompteur { get; set; }
        public virtual DbSet<Manufacturiers> Manufacturiers { get; set; }
        public virtual DbSet<MotifsCommandeCylindreRef> MotifsCommandeCylindreRef { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Pannes> Pannes { get; set; }
        public virtual DbSet<ParticularitesUsagerRef> ParticularitesUsagerRef { get; set; }
        public virtual DbSet<PeriodesFinancieresRef> PeriodesFinancieresRef { get; set; }
        public virtual DbSet<PretsEquipement> PretsEquipement { get; set; }
        public virtual DbSet<ReglesNotification> ReglesNotification { get; set; }
        public virtual DbSet<Reparations> Reparations { get; set; }
        public virtual DbSet<SecteursSRSAD> SecteursSRSAD { get; set; }
        public virtual DbSet<SeuilsInventaire> SeuilsInventaire { get; set; }
        public virtual DbSet<StatutsDossierUsager> StatutsDossierUsager { get; set; }
        public virtual DbSet<StatutsEquipementRef> StatutsEquipementRef { get; set; }
        public virtual DbSet<StatutsSuivi> StatutsSuivi { get; set; }
        public virtual DbSet<TypesAcquisitionRef> TypesAcquisitionRef { get; set; }
        public virtual DbSet<TypesCylindreRef> TypesCylindreRef { get; set; }
        public virtual DbSet<TypesEquipement> TypesEquipement { get; set; }
        public virtual DbSet<TypesFinancementRef> TypesFinancementRef { get; set; }
        public virtual DbSet<TypesInfection> TypesInfection { get; set; }
        public virtual DbSet<TypesInfestation> TypesInfestation { get; set; }
        public virtual DbSet<TypesIntervenant> TypesIntervenant { get; set; }
        public virtual DbSet<TypesLivraisonRef> TypesLivraisonRef { get; set; }
        public virtual DbSet<TypesPanneRef> TypesPanneRef { get; set; }
        public virtual DbSet<UsagerAdresses> UsagerAdresses { get; set; }
        public virtual DbSet<UsagerInfections> UsagerInfections { get; set; }
        public virtual DbSet<UsagerInfestations> UsagerInfestations { get; set; }
        public virtual DbSet<UsagerParticularites> UsagerParticularites { get; set; }
        public virtual DbSet<Usagers> Usagers { get; set; }
        public virtual DbSet<Visites> Visites { get; set; }
    }
}
